### PR TITLE
delete generated file __README.TXT

### PR DESCRIPTION
**Pull request by digama0**
See also https://github.com/metamath/metamath-website-seed/pull/18

### CODE REVIEW

**Comment by benjub** [comment]
Why delete `symbols/mm.gif` ? It looks like it's used in https://github.com/metamath/symbols/blob/1694dbc13d72bae2f96fb13671616d6ef3e3f9eb/symbols/symbols.html#L30

And by the way: the link to `../index.html` on that line is broken.

**Comment by digama0** [comment]
> Why delete `symbols/mm.gif` ? 

It's copied from https://github.com/metamath/metamath-website-seed/blob/main/mm.gif into the symbols folder as part of the website build. Similarly, the `../index.html` link works within the context of the site.

**Comment by benjub** [comment]
> It's copied from https://github.com/metamath/metamath-website-seed/blob/main/mm.gif into the symbols folder as part of the website build. Similarly, the `../index.html` link works within the context of the site.

Oh, I thought it was a standalone repo, my bad. Then, we should probably merge it with the `website` repo (the fusion of `metamath-website-seed` and `metamath-website-script`) ?

Or if we want to keep it as standalone, we can use an absolute link instead of a relative link (both for the link and the resource) ?

**Comment by benjub** [comment]
Just to be clear: my previous comment does not block the merging of this PR: the merging of the repositories or the transition to absolute links can be done as a second step.

**Review by benjub — APPROVED** [review]

**Comment by digama0** [comment]
If no one objects I will merge all the PRs in this series in about 24 hours, unless there are additional concerns brought up (please speak up if you think something is out of place).

**Pull request merged**
